{
    'name': 'Request Maintenance',
    'version': '1.0',
    'summary': 'Module quản lý yêu cầu bảo trì',
    'sequence': 100,
    'description': """Quản lý yêu cầu bảo trì và kiểm duyệt thiết bị""",
    'category': 'Maintenance',
    'website': 'https://yourcompany.com',
    'depends': ['mail'], 
    'data': [
        'security/ir.model.access.csv',  
        'security/ir.rule.xml',         
        'data/maintenance_request_data.xml',      
        'data/maintenance_stage.xml',
        'data/data.xml',
        'views/maintenance_request.xml', 
        'views/maintenance_category.xml',
        'wizards/maintenance_wizard_view.xml',
        'report/equipment_report.xml',
        'report/equipment_report_template.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
    'assets': {
        'web.assets_backend': [
            'static/description/index.html',
        ],
    },
    'license': 'LGPL-3',
}
